---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ apicurio_operator_operator_name }}"
    install_operator_namespace: "{{ apicurio_operator_operator_namespace }}"
    install_operator_channel: "{{ apicurio_operator_channel }}"
    install_operator_csv_nameprefix: "{{ apicurio_operator_csv_prefix }}"
    install_operator_catalog: "{{ apicurio_operator_operator_catalog }}"
    install_operator_automatic_install_plan_approval:
      "{{ apicurio_operator_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ apicurio_operator_starting_csv }}"
    install_operator_manage_namespaces:
      - "{{ apicurio_operator_operator_namespace }}"
    install_operator_catalogsource_setup: "{{ apicurio_operator_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ apicurio_operator_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: openshift-operators
    install_operator_catalogsource_image: "{{ apicurio_operator_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ apicurio_operator_catalog_snapshot_image_tag | default('') }}"

- name: Wait until the operator is up and running
  when: apicurio_operator_wait_for_deploy | bool
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: deployment
    name: "{{ apicurio_operator_deployment }}"
    namespace: "{{ apicurio_operator_operator_namespace }}"
  register: r_apicurio_deployment
  retries: 40
  delay: 15
  until:
    - r_apicurio_deployment.resources is defined
    - r_apicurio_deployment.resources | length | int > 0
    - r_apicurio_deployment.resources[0].status.availableReplicas is defined
    - r_apicurio_deployment.resources[0].status.availableReplicas | int == r_apicurio_deployment.resources[0].spec.replicas | int
