---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: remove
    install_operator_name: "{{ threescale_operator_name }}"
    install_operator_namespace: "{{ threescale_operator_namespace }}"
    install_operator_channel: "{{ threescale_operator_channel }}"
    install_operator_catalog: "{{ threescale_operator_catalog }}"
    install_operator_catalogsource_setup:
      "{{ threescale_operator_use_catalog_snapshot | default(false) }}"
