---
# Implement your workload removal tasks here
# ------------------------------------------

- name: Remove Apicurio Designer operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: remove
    install_operator_name: "{{ apicurio_operator_operator_name }}"
    install_operator_namespace: "{{ apicurio_operator_operator_namespace }}"
    install_operator_channel: "{{ apicurio_operator_channel }}"
    install_operator_catalog: "{{ apicurio_operator_operator_catalog }}"
    install_operator_catalogsource_setup:
      "{{ apicurio_operator_use_catalog_snapshot | default(false) }}"
