---
# Implement your workload removal tasks here
# ------------------------------------------

- name: Remove AMQ Streams operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: remove
    install_operator_name: "{{ amq_streams_operator_name }}"
    install_operator_namespace: "{{ amq_streams_operator_namespace }}"
    install_operator_channel: "{{ amq_streams_operator_channel }}"
    install_operator_catalog: "{{ amq_streams_operator_catalog }}"
    install_operator_catalogsource_setup:
      "{{ amq_streams_operator_use_catalog_snapshot | default(false) }}"
