---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: remove
    install_operator_name: "{{ service_registry_operator_name }}"
    install_operator_namespace: "{{ service_registry_operator_namespace }}"
    install_operator_channel: "{{ service_registry_channel }}"
    install_operator_catalog: "{{ service_registry_operator_catalog }}"
    install_operator_catalogsource_setup:
      "{{ service_registry_use_catalog_snapshot | default(false) }}"
