---

- name: Install Service Binding operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ service_binding_operator_name }}"
    install_operator_namespace: "{{ service_binding_operator_namespace }}"
    install_operator_channel: "{{ service_binding_operator_channel }}"
    install_operator_automatic_install_plan_approval: >-
      {{ service_binding_operator_automatic_install_plan_approval }}
    install_operator_starting_csv: "{{ service_binding_operator_starting_csv }}"
    install_operator_csv_nameprefix: "{{ service_binding_operator_csv_nameprefix }}"
    install_operator_catalog: "{{ service_binding_operator_catalog }}"
    install_operator_catalogsource_setup: "{{ service_binding_operator_use_catalog_snapshot }}"
    install_operator_catalogsource_name: "{{ service_binding_operator_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: openshift-operators
    install_operator_catalogsource_image:
      "{{ service_binding_operator_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ service_binding_operator_catalog_snapshot_image_tag | default('') }}"
