---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ service_registry_operator_name }}"
    install_operator_namespace: "{{ service_registry_operator_namespace }}"
    install_operator_channel: "{{ service_registry_channel }}"
    install_operator_csv_nameprefix: "{{ service_registry_csv_prefix }}"
    install_operator_catalog: "{{ service_registry_operator_catalog }}"
    install_operator_automatic_install_plan_approval:
      "{{ service_registry_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ service_registry_starting_csv }}"
    install_operator_catalogsource_setup: "{{ service_registry_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ service_registry_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: openshift-operators
    install_operator_catalogsource_image: "{{ service_registry_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ service_registry_catalog_snapshot_image_tag | default('') }}"
