---

- name: Create usernames
  ansible.builtin.set_fact:
    _users: |
       {{ _users |
       default([]) + [user_prefix + item | string] }}
  loop: "{{ range(1, ((user_count | int) + 1)) | list }}"

- name: "Create {{ user_count }} namespaces for bookbag"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'bookbag/namespace-bookbag.yaml.j2') }}"
  vars:
    __bookbagnamespaces:
      - "{{ bookbag_namespace_prefix }}user"
  retries: 10
  delay: 30

- name: Deploy applicationset
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'bookbag/applicationset-bookbag.yaml.j2') | from_yaml }}"

- name: Print bookbag url for each user
  agnosticd_user_info:
    user: "{{ user_prefix }}{{ n }}"
    data:
      instructions_url: >-
        https://bookbag-bookbag-{{ user_prefix }}{{ n }}.{{ r_openshift_subdomain }}
  loop: "{{ range(1, 1 + user_count | int) | list }}"
  loop_control:
    loop_var: n
