---

- name: Install OpenShift Pipelines operator
  ansible.builtin.include_tasks: openshift_pipelines_operator.yml

- name: Install OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops.yml

- name: Install 3scale operator
  when: lab_setup | bool
  ansible.builtin.include_tasks: threescale_operator.yml

- name: Install Apicurio Designer operator
  when: lab_setup | bool
  ansible.builtin.include_tasks: apicurio_designer_operator.yml

- name: Install Service Registry operator
  when: lab_setup | bool
  ansible.builtin.include_tasks: service_registry_operator.yml


- name: Deploy 3scale and tenants
  when: lab_setup | bool
  ansible.builtin.include_tasks: threescale.yml

- name: Install Apicurio Designer application
  when: lab_setup | bool
  ansible.builtin.include_tasks: apicurio_designer.yml

- name: Set up app for api modules
  when: lab_setup | bool
  ansible.builtin.include_tasks: setup_app_services.yml
